### ISSUE TITLE
error: undefined method `pool_identity`

### ISSUE THREAD

**Issue by spuder** [opscode-cookbooks/iis#128]
If you run this cookbook on a brand new windows 2012r2 server, you will get the following error

undefined method `pool_identity`

```
==> default: [2015-02-11T12:28:01-08:00] INFO: Chef-client pid: 3812
==> default: [2015-02-11T12:28:10-08:00] INFO: Setting the run_list to ["recipe[ND-Webserver2012]"] from CLI options
==> default:
==> default: [2015-02-11T12:28:10-08:00] INFO: Run List is [recipe[ND-Webserver2012]]
==> default: [2015-02-11T12:28:10-08:00] INFO: Run List expands to [ND-Webserver2012]
==> default: [2015-02-11T12:28:10-08:00] INFO: Starting Chef Run for vagrant-2012-r2.nv.com
==> default: [2015-02-11T12:28:10-08:00] INFO: Running start handlers
==> default: [2015-02-11T12:28:10-08:00] INFO: Start handlers complete.
==> default: ================================================================================
==> default: Recipe Compile Error in C:/tmp/vagrant-chef-3/chef-solo-1/cookbooks/ND-Webserver2012/recipes/default.rb
==> default: ================================================================================
==> default:
==> default: NoMethodError
==> default: -------------
==> default: undefined method `pool_identity' for Chef::Resource::IisPool
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/resource.rb:300:in `method_missing'
==> default:   C:/tmp/vagrant-chef-3/chef-solo-1/cookbooks/ND-Webserver2012/recipes/default.rb:28:in `block in from_file'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/dsl/recipe.rb:136:in `instance_eval'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/dsl/recipe.rb:136:in `build_resource'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/dsl/recipe.rb:85:in `declare_resource'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/dsl/recipe.rb:41:in `method_missing'
==> default:   C:/tmp/vagrant-chef-3/chef-solo-1/cookbooks/ND-Webserver2012/recipes/default.rb:24:in `from_file'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/cookbook_version.rb:234:in `load_recipe'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/run_context.rb:166:in `load_recipe'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/run_context.rb:89:in `load'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/client.rb:265:in `setup_run_context'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/client.rb:429:in `do_run'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/client.rb:227:in `run'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/application.rb:236:in `run_chef_client'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/application/solo.rb:226:in `block in run_application'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/application/solo.rb:218:in `loop'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/application/solo.rb:218:in `run_application'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/application.rb:55:in `run'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/bin/chef-solo:25:in `<top (required)>'
==> default:   C:/opscode/chef/bin/chef-solo:23:in `load'
==> default:   C:/opscode/chef/bin/chef-solo:23:in `<main>'
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/resource.rb:
==> default:
==> default: 293:      # If an unknown method is invoked, determine whether the enclosing Provider's
==> default: 294:      # lexical scope can fulfill the request. E.g. This happens when the Resource's
==> default: 295:      # block invokes new_resource.
==> default: 296:      def method_missing(method_symbol, *args, &block)
==> default: 297:        if enclosing_provider && enclosing_provider.respond_to?(method_symbol)
==> default: 298:          enclosing_provider.send(method_symbol, *args, &block)
==> default: 299:        else
==> default: 300>>         raise NoMethodError, "undefined method `#{method_symbol.to_s}' for #{self.class.to_s}"
==> default: 301:        end
==> default: 302:      end
==> default: 303:
==> default: 304:      def load_prior_resource
==> default: 305:        begin
==> default: 306:          prior_resource = run_context.resource_collection.lookup(self.to_s)
==> default: 307:          # if we get here, there is a prior resource (otherwise we'd have jumped
==> default: 308:          # to the rescue clause).
==> default: 309:          Chef::Log.warn("Cloning resource attributes for #{self.to_s} from prior resource (CHEF-3694)")
==> default:
==> default: [2015-02-11T12:28:19-08:00] ERROR: Running exception handlers
==> default: [2015-02-11T12:28:19-08:00] ERROR: Exception handlers complete
==> default: [2015-02-11T12:28:19-08:00] FATAL: Stacktrace dumped to C:/var/chef/cache/chef-stacktrace.out
==> default: [2015-02-11T12:28:19-08:00] FATAL: NoMethodError: undefined method `pool_identity' for Chef::Resource::IisPool
Chef never successfully completed! Any errors should be visible in the
```

recipe/default.rb

```ruby
iis_pool 'foobar' do
  runtime_version 'v4.0'
  pipeline_mode :Integrated
  thirty_two_bit :true
  pool_identity :SpecificUser
  pool_username 'exampleuser'
  pool_password 'correct-horse-battery-staple'
  action [:add,:start]
end
```

I'm pretty new to chef, so I'm not sure if this is a bug or a configuration problem.

**Comment by spuder** [comment]
I've figured it out. For some reason, chef was downloading an older version. 

By adding the following to my berksfile and metadata.rb of my wrapper cookbook, I no longer get the error. 

metadata.rb

    depends 'iis', '~> 3.0.12'

berksfile

    cookbook 'iis', git: 'https://github.com/opscode-cookbooks/iis.git'
