### ISSUE TITLE
iis_site bindings are not working, documentation could use some examples

### ISSUE THREAD

**Issue by christrotter** [opscode-cookbooks/iis#98]
There was some discussion in this issue: https://github.com/opscode-cookbooks/iis/issues/95

Version info:
1. chef-server 12.0.1
2. client: chef-windows-11.14.2-1.windows.msi
3. Node is 2008R2.
4. I'm using the IIS 3.0.4 hotfix branch...https://github.com/EasyAsABC123/iis/tree/hotfix_helper-class

Here is what I'm trying:
``` ruby
 iis_site "#{cookbook_name}" do
	bindings "http/*:80:www.domain.com","https/*:443:"
	action [:config,:restart]
 end
```

Here's what I get:
``` powershell
nodeName
nodeName ================================================================================
nodeName Recipe Compile Error in c:/chef/cache/cookbooks/CookbookName/recipes/default.rb
nodeName ================================================================================
nodeName
nodeName ArgumentError
nodeName -------------
nodeName wrong number of arguments (2 for 1)
nodeName
nodeName Cookbook Trace:
nodeName ---------------
nodeName   c:/chef/cache/cookbooks/CookbookName/recipes/default.rb:44:in `block in from_file'
nodeName   c:/chef/cache/cookbooks/CookbookName/recipes/default.rb:43:in `from_file'
nodeName
nodeName Relevant File Content:
nodeName ----------------------
nodeName c:/chef/cache/cookbooks/CookbookName/recipes/default.rb:
nodeName
nodeName  37:         path "c:\\web\\data\\#{cookbook_name}"
nodeName  38:         site_name "#{cookbook_name}"
nodeName  39:         application_pool "#{cookbook_name}"
nodeName  40:         action [:add,:start]
nodeName  41:   end
nodeName  42:
nodeName  43:   iis_site "#{cookbook_name}" do
nodeName  44>>        bindings "http/*:80:www.domain.com","https/*:443:"
nodeName  45:         action [:config,:restart]
nodeName  46:   end
nodeName  47:
nodeName  48:
nodeName  49:   # iis_site "#{cookbook_name}" do
nodeName  50:         #path "c:/web/data/#{cookbook_name}"
nodeName  51:
nodeName  52:         # STDOUT: ERROR ( message:Invalid format for parameter "bindings" -
nodeName  53:         # it must be of the following format:
nodeName
nodeName [2015-01-02T10:55:56-05:00] ERROR: Running exception handlers
nodeName [2015-01-02T10:55:56-05:00] ERROR: Exception handlers complete
nodeName [2015-01-02T10:55:56-05:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
nodeName [2015-01-02T10:55:56-05:00] FATAL: ArgumentError: wrong number of arguments (2 for 1)
```

Other pieces of my recipe: (these come before the bindings section)
``` ruby
 iis_pool "#{cookbook_name}" do
    action :recycle
 end
 
 iis_site "#{cookbook_name}" do
	path "c:\\web\\data\\#{cookbook_name}"
	site_name "#{cookbook_name}"
	application_pool "#{cookbook_name}"
	action [:add,:start]
 end
```

Oh yeah - and as mentioned in that other issue, would be great to see some examples for the other options like bindings.

**Comment by christrotter** [comment]
Oh yeah, and if I leave out the second bindings piece (https) like this:
``` ruby
 iis_site "#{cookbook_name}" do
	bindings "http/*:80:www.domain.com"
	action [:config,:restart]
 end
```

I get this:
``` powershell
nodeName
nodeName ================================================================================
nodeName Error executing action `config` on resource 'iis_site[CookbookName]'
nodeName ================================================================================
nodeName
nodeName ArgumentError
nodeName -------------
nodeName wrong number of arguments (0 for 1)
nodeName
nodeName Cookbook Trace:
nodeName ---------------
nodeName c:/chef/cache/cookbooks/iis/libraries/helper.rb:62:in `appcmd'
nodeName c:/chef/cache/cookbooks/iis/providers/site.rb:73:in `block in class_from_file'
nodeName
nodeName Resource Declaration:
nodeName ---------------------
nodeName # In c:/chef/cache/cookbooks/CookbookName/recipes/default.rb
nodeName
nodeName  43:  iis_site "#{cookbook_name}" do
nodeName  44:         bindings "http/*:80:www.domain.com"
nodeName  45:         action [:config,:restart]
nodeName  46:  end
nodeName  47:
nodeName
nodeName Compiled Resource:
nodeName ------------------
nodeName
nodeName # Declared in c:/chef/cache/cookbooks/CookbookName/recipes/default.rb:43:in `from_file'
nodeName
nodeName iis_site("CookbookName") do
nodeName   action [:config, :restart]
nodeName   retries 0
nodeName   retry_delay 2
nodeName   guard_interpreter :default
nodeName   cookbook_name "CookbookName"
nodeName   recipe_name "default"
nodeName   path "c:\\web\\data\\CookbookName"
nodeName   site_name "CookbookName"
nodeName   application_pool "CookbookName"
nodeName   bindings "http/*:80:www.domain.com"
nodeName   protocol :http
nodeName   port 80
nodeName end
nodeName
nodeName [2015-01-02T11:04:49-05:00] ERROR: Running exception handlers
nodeName [2015-01-02T11:04:49-05:00] ERROR: Exception handlers complete
nodeName [2015-01-02T11:04:49-05:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
nodeName [2015-01-02T11:04:49-05:00] FATAL: ArgumentError: iis_site[CookbookName] (CookbookName::default line 43) had an error: ArgumentError: wrong number of arguments (0 for 1)
```

**Comment by christrotter** [comment]
Realized your dev/iis readme was updated with examples, so copied those:  
```ruby
 iis_site "#{cookbook_name}" do
	bindings "http/*:80:scihome.scitorque.com,https/*:443:scihome.scitorque.com"
	action [:config,:restart]
        #(I tried the [:add,:start] - that didn't apply any bindings, although no error)
 end
```

```powershell
nodeName
nodeName ================================================================================
nodeName Error executing action `config` on resource 'iis_site[CookbookName]'
nodeName ================================================================================
nodeName
nodeName ArgumentError
nodeName -------------
nodeName wrong number of arguments (0 for 1)
nodeName
nodeName Cookbook Trace:
nodeName ---------------
nodeName c:/chef/cache/cookbooks/iis/libraries/helper.rb:62:in `appcmd'
nodeName c:/chef/cache/cookbooks/iis/providers/site.rb:73:in `block in class_from_file'
nodeName
nodeName Resource Declaration:
nodeName ---------------------
nodeName # In c:/chef/cache/cookbooks/CookbookName/recipes/default.rb
nodeName
nodeName  43:  iis_site "#{cookbook_name}" do
nodeName  44:         bindings "http/*:80:www.domain.com,https/*:443:www.domain.com"
nodeName  45:         action [:config,:restart]
nodeName  46:  end
nodeName  47:
nodeName
nodeName Compiled Resource:
nodeName ------------------
nodeName # Declared in c:/chef/cache/cookbooks/CookbookName/recipes/default.rb:43:in `from_file'
nodeName
nodeName iis_site("CookbookName") do
nodeName   action [:config, :restart]
nodeName   retries 0
nodeName   retry_delay 2
nodeName   guard_interpreter :default
nodeName   cookbook_name "CookbookName"
nodeName   recipe_name "default"
nodeName   path "c:\\web\\data\\CookbookName"
nodeName   site_name "CookbookName"
nodeName   application_pool "CookbookName"
nodeName   bindings "http/*:80:www.domain.com,https/*:443:www.domain.com"
nodeName   protocol :http
nodeName   port 80
nodeName end
nodeName
nodeName [2015-01-02T11:14:24-05:00] ERROR: Running exception handlers
nodeName [2015-01-02T11:14:24-05:00] ERROR: Exception handlers complete
nodeName [2015-01-02T11:14:24-05:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
nodeName [2015-01-02T11:14:24-05:00] FATAL: ArgumentError: iis_site[CookbookName] (CookbookName::default line 43) had an error: ArgumentError: wrong number of arguments (0 for 1)
```

**Comment by EasyAsABC123** [comment]
Running chef-client `11.14.2-1` using chef-client -z for testing, iis@3.0.5
Windows Server 2012r2 x64

bindings seem to work now, please verify
remember to grab latest, same branch

**Comment by christrotter** [comment]
Working!!  Very nicely done, sir.  Let me know if you need any other testing done, I'm in your debt!

**Comment by EasyAsABC123** [comment]
happy to hear it, just going to work with @btm to get this pull request moved in and I think i've got 99% of the issues resolved.  Thanks to all your testing, it is greatly appreciated.  Sorry I had some bugs on the bindings part didn't mean to make it seem more confusing than it was.

Have a good one.
